### PR TITLE
Fix inverse_cdf for StudentsT.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Closes gh-156.

### CODE REVIEW

**Comment by troublescooter** [comment]
Thanks for the fix. I'll review it this weekend.

**Comment by WarrenWeckesser** [comment]
@troublescooter, I noticed a problem with the PR, and since I don't think anyone has taken a close look at this yet, I force-pushed an update.

**Comment by troublescooter** [comment]
I'll use this opportunity to move over the tests to the new testing macro seen in [internal.rs](https://github.com/statrs-dev/statrs/blob/master/src/distribution/internal.rs) which has not yet been applied to StudentsT. This takes care of the targeted relative accuracy. This will take a day or two, otherwise LGTM.

**Comment by troublescooter** [comment]
Thanks!

**Pull request merged**
