### PR TITLE
Specialize inverse_cdf for LogNormal distribution

### PR DESCRIPTION
**Pull request by Twister915**
# Description

Specialize `inverse_cdf` for `LogNormal` distribution, because an equation exists and it is faster & more accurate than the default binary search implementation.

# Changes

* Adds a definition for `inverse_cdf` in `ContinuousCDF` impl for `LogNormal` distribution, according to [the definition I read here](https://www.wolframalpha.com/input/?i=inverse+CDF+LogNormal) and some pen & paper verification of this definition.
* Generalizes the unit tests in LogNormal such that the CDF test cases are re-used (where applicable) to verify the inverse CDF definition

# Review Notes

* I'm no mathematician so someone definitely needs to verify my implementation. I am not sure if the wolfram-alpha I linked above is the most general definition of the inverse CDF. 
   * Wikipedia (seemingly) has a different definition which includes `erf_inverse`, and I don't know how `erf_inverse` relates to `erfc_inverse`.
   * I inverted the CDF definition myself (using my basic algebra skills) on pen & paper and it matched the wolfram-alpha math, so that's what I implemented.
* The unit testing section will perform the exact same test cases for the CDF, despite all the code changes. There is one exception: a change to the accuracy argument on the case where input=`0.5` and output=`0.0000000015011556178148777579869633555518882664666520593658`.

### CODE REVIEW

**Comment by henryjac** [comment]
erfc is the complementary error function, so ``erfc(x) = 1 - erf(x)``. Wikipedia and wolfram alpha give the same math as your code, so that checks out. Will check the test

**Comment by YeungOnion** [comment]
merge edits
- added `}` since added functions within `impl ContinuousCDF for LogNormal` were adjacent
- math in docs should be `text` instead of `ignore` with [b8a0ec2](https://github.com/statrs-dev/statrs/commit/b8a0ec248d1ed25b268411897464befe46f5e385)

I too like the symmetric tests.

@henryjac iirc you wanted to rebase and merge so merge commits would represent PRs in history. Would you prefer that @Twister915 redo the changes atop master so we can rebase instead and keep that up?

**Comment by YeungOnion** [comment]
Opted to do a local merge and push to master, will have to close this one manually.

If anyone knows a way to manually modify this PR to "close as merged" by a specific commit, the SHA is ae5431fb0805cb89d84bb5dbd3aea17833dba97e

Thanks for implementing this!

**Comment by YeungOnion** [comment]
Opted to do a local merge and push to master, will have to close this one manually.

If anyone knows a way to manually modify this PR to "close as merged" by a specific commit, the SHA is ae5431fb0805cb89d84bb5dbd3aea17833dba97e

Thanks for implementing this along with a thorough write-up!

**Comment by YeungOnion** [comment]
Opted to do a local merge and push to master, will have to close this one manually.

If anyone knows a way to manually modify this PR to "close as merged" by a specific commit, the SHA is ae5431fb0805cb89d84bb5dbd3aea17833dba97e

Thanks for implementing this along with a thorough write-up!

**Pull request closed without merging**
